[package]
name = "ccm-primitives"
version = "1.0.0"
edition = "2021"
license = "MIT"
description = "Core primitives for Coherence-Centric Mathematics (CCM)."
repository = "https://git.example.org/ccm/ccm-primitives"

[features]
default = ["std", "sha2"]
std = []                # pulls in std::vec, std::error, etc.
alloc = []             # for no_std + alloc
bigint = ["num-bigint"] # Î± beyond 128-bit mantissa
binary128 = ["rug"]     # quad-precision floats
ct = ["subtle"]         # constant-time comparisons
sha2 = ["dep:sha2"]     # SHA-256 integrity tags

[dependencies]
num-bigint = { version = "0.4", optional = true }
num-traits = { version = "0.2", default-features = false, features = ["libm"] }
rug = { version = "1.24", optional = true, features = ["float"] }
subtle = { version = "2.5", optional = true }
sha2 = { version = "0.10", optional = true }

[dev-dependencies]
proptest = "1.4"