[package]
name = "ccm-coherence"
version = "0.1.0"
edition = "2021"
authors = ["UOR Contributors"]
description = "Clifford algebra and coherence metric for CCM"
license = "MIT"
repository = "https://github.com/UOR-Foundation/PrimeOS"

[dependencies]
ccm-core = { path = "../ccm-core" }
num-traits = { version = "0.2", default-features = false }
num-complex = { version = "0.4", default-features = false }

[features]
default = ["std"]
std = ["ccm-core/std", "num-traits/std", "num-complex/std"]
alloc = ["ccm-core/alloc", "num-complex/libm"]

[dev-dependencies]